### ISSUE TITLE
Changes you made to Startup.cs cause below error

### ISSUE THREAD

**Issue by PeterJD** [maraf/Money#220]
Money.UI.Backend
----------------------------------------------------------
An unhandled exception occurred while processing the request.
InvalidOperationException: No authentication handler is registered for the scheme 'Cookies'. The registered schemes are: Bearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Cookies",...)?
Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, string scheme, AuthenticationProperties properties)

Stack Query Cookies Headers
InvalidOperationException: No authentication handler is registered for the scheme 'Cookies'. The registered schemes are: Bearer, Identity.Application, Identity.External, Identity.TwoFactorRememberMe, Identity.TwoFactorUserId. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Cookies",...)?
Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, string scheme, AuthenticationProperties properties)
Money.Startup+<>c+<<Configure>b__5_2>d.MoveNext() in Startup.cs
+
                    await context.ChallengeAsync(CookieAuthenticationDefaults.AuthenticationScheme);
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by PeterJD** [comment]
line 138

**Comment by maraf** [comment]
Hi @PeterJD.
I know that, all commits related to the #218 are work in progress. 
I'm going to completely remove the `Money.UI.Backend` and advance to an api-centric version, in the `Money.Api`.

If you want latest working version, please use tag `blazor-v1.7.0`.

**Comment by PeterJD** [comment]
Hi
Ok thanks for the info
Peter

**Comment by maraf** [comment]
I'm going to close this one. If you have any further questions, feel free to ask.

**Comment by engmohamedcs** [comment]
What is the solution?

**Comment by maraf** [comment]
We don't use cookies for a long time. When code was migrated to `Money.Api`, the authentication moved to bearer tokens.
