### ISSUE TITLE
SQLite Error 1: 'table "Categories" already exists'.

### ISSUE THREAD

**Issue by zunichky** [maraf/Money#410]
Trying to run blazor app from latest commit from tip of master, and keep keeping a migration error. I tried switching to sqlserver, but still am getting error. I went back like 6 months, and was able to run it, but once I switched back, the error happened again. Any suggestions?  

Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "Categories" (
    "Id" TEXT NOT NULL CONSTRAINT "PK_Categories" PRIMARY KEY,
    "UserId" TEXT NULL,
    "Name" TEXT NULL,
    "Description" TEXT NULL,
    "Icon" TEXT NULL,
    "ColorA" INTEGER NOT NULL,
    "ColorR" INTEGER NOT NULL,
    "ColorG" INTEGER NOT NULL,
    "ColorB" INTEGER NOT NULL,
    "IsDeleted" INTEGER NOT NULL
);
SQLite Error 1: 'table "Categories" already exists'.

**Comment by maraf** [comment]
Sorry for late reply, I was on vacation.

There was really a bug calling both `EnsureCreated` and `Migrate` on EF context.
It is now fixed.

Thank you for the report.

**Comment by zunichky** [comment]
No problem! I thought I tried that but must have forgot one of the `EnsureCreated`.  Anyways, it's working for me now. I appreciate it!
